/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicholas Peng Gen
 */
public class EditUserDetails extends javax.swing.JFrame {
    private final String id;
    private final String email;

    /**
     * Creates new form EditPersonalDetails
     * @param id
     */
    public EditUserDetails(String id) {
        initComponents();
        this.id = id;
        String username;
        String fname;
        String lname;
        String email = "";
        String number;
        String status;
        try  
        {  
            BufferedReader data;
            data = new BufferedReader(new FileReader("files/users.txt"));
            String line;
            data.readLine(); // Read the header row
            while((line = data.readLine()) != null)
            {
                if(id.compareTo(line.split("\t")[0]) == 0)
                {
                    //System.out.println(line);
                    username = line.split("\t")[1];
                    fname = line.split("\t")[2];
                    lname = line.split("\t")[3];
                    email = line.split("\t")[4];
                    number = line.split("\t")[6];
                    status = line.split("\t")[7];
                    data.close();
                    jTextField1.setText(username);
                    jTextField2.setText(fname);
                    jTextField3.setText(lname);
                    jTextField5.setText(email);
                    jTextField4.setText(number);
                    jComboBox1.setSelectedItem(status);
                    break;
                    
                }
                

            }
            

            data.close();
        }  
        catch(IOException e)  
        {  
            
            e.printStackTrace();  
        }
        
        this.email = email;
        
        
        
    }

    private EditUserDetails() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Account Settings");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 600, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 100, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("E-mail:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check Feedback History");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 250, 45));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 370, 125, 45));

        jTextField1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 200, -1));

        jTextField2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 200, -1));

        jTextField3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 200, -1));

        jTextField4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 200, -1));

        jTextField5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 200, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 125, 45));

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending", "Rejected" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 200, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telephone Number:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reset password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 180, 45));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Check Order History");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 250, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 600, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/Pictures/pexels-lisa-fotios-1279330 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        
        UserManagement umf = new UserManagement();
        umf.setLocation(this.getLocation());
        umf.setResizable(false);
        umf.setVisible(true);

        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = jTextField1.getText();
        String fname = jTextField2.getText();
        String lname = jTextField3.getText();
        String email = jTextField5.getText();
        String number = jTextField4.getText();
        String status = jComboBox1.getSelectedItem().toString();
        
        //First check length
        if(username.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Username cannot be empty", "Username Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try  
        {  
              
            BufferedReader data;
            data = new BufferedReader(new FileReader("files/users.txt"));
            String line;
            data.readLine(); // Read the header row
            while((line = data.readLine()) != null)
            {
               
                if(this.id.compareTo(line.split("\t")[0]) != 0 && username.compareTo(line.split("\t")[1]) == 0)
                {
                    JOptionPane.showMessageDialog(this, "Username already taken", "Username Error", JOptionPane.ERROR_MESSAGE);
                    data.close();
                    return;
                }

            }//while

            data.close();
        }  
        catch(IOException e)  
        {  
            
            e.printStackTrace();  
        }
        if(username.length() < 5)
        {
            JOptionPane.showMessageDialog(this, "Username length cannot be less than 5", "Username Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(username.length() > 15)
        {
            JOptionPane.showMessageDialog(this, "Username length cannot be more than 15", "Username Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Check the first letter
        char a = username.charAt(0);
        if(!((a >= 'a' && a <= 'z') || (a >= 'A' && a <= 'Z')))
        {
            JOptionPane.showMessageDialog(this, "Username must start with a letter", "Username Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Check for alpha numeric and -_.
        for (int i = 0; i < username.length(); i++)
        {
            char b = username.charAt(i);
            if (!((b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z') || (b >= '0' && b <= '9') || b == '-' || b == '_' || b == '.'))
            {
                JOptionPane.showMessageDialog(this, "Username can only contain letters, numbers, dot, dash and underscore", "Username Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        
        
        
        //First Name validity
        if(fname.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "First Name cannot be empty", "First Name Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Last Name validity
        if(lname.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Last Name cannot be empty", "Last Name Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        
        //Email validity
        if(email.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Email cannot be empty", "Email Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!email.endsWith("@mail.apu.edu.my") && !email.endsWith("@staffmail.apu.edu.my") && !email.endsWith("@apu.edu.my"))
        {
            JOptionPane.showMessageDialog(null, "Email must be an APU email", "Email Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try  
        {  
              
            BufferedReader data;
            data = new BufferedReader(new FileReader("files/users.txt"));
            String line;
            data.readLine(); // Read the header row
            while((line = data.readLine()) != null)
            {
                if(this.id.compareTo(line.split("\t")[0]) != 0 && email.compareTo(line.split("\t")[4]) == 0)
                {
                    JOptionPane.showMessageDialog(this, "There is an account with this email already.", "Email Error", JOptionPane.ERROR_MESSAGE);
                    data.close();
                    return;
                }

            }//while

            data.close();
        }  
        catch(IOException e)  
        {  
            
            e.printStackTrace();  
        }
        
        //Phone Number validity
        if(number.length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Phone Number cannot be empty", "Phone Number Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!number.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number", "Phone Number Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Update the file
        try  
        {  
            
            BufferedReader data;
            data = new BufferedReader(new FileReader("files/users.txt"));
            StringBuilder inputBuffer = new StringBuilder();
            String line;
            line = data.readLine(); // Read the header row
            inputBuffer.append(line).append("\n");
                
            while((line = data.readLine()) != null)
            {
                if(this.id.compareTo(line.split("\t")[0]) == 0)
                {
                    
                    line = this.id + "\t"+ username + "\t"+ fname + "\t" + lname + "\t" + email + "\t" + line.split("\t")[5] + "\t" + number + "\t" + status + "\t" + line.split("\t")[8] + "\t" + line.split("\t")[9];
                    
                }
                
                inputBuffer.append(line).append("\n");
                
            }
            data.close();
            
            //FileWriter fw;
            //fw = new FileWriter("files/users.txt", true);

//            fw.write(inputBuffer.toString().getBytes());
            FileOutputStream fileOut;
            fileOut = new FileOutputStream("files/users.txt");
            fileOut.write(inputBuffer.toString().getBytes());
            fileOut.close();
            //fw.close();
            
            
//            File oldFile = new File("files/users.txt");
//            File newFile = new File("files/temp.txt");
//            data.
//            System.out.println(newFile.delete());
//            newFile.delete();
//            File dump = new File("files/users.txt");
//            newFile.renameTo(dump);
            

            this.setVisible(false);
            UserManagement umf = new UserManagement();
            umf.setLocation(this.getLocation());
            umf.setResizable(false);
            umf.setVisible(true);
            
            
        }  
        catch(IOException e)  
        {  
           
            e.printStackTrace();  
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        FeedbackReport frf = new FeedbackReport(this.email);
        frf.setLocation(this.getLocation());
        frf.setResizable(false);
        frf.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        ResetPassLoggedIn rplf = new ResetPassLoggedIn(this.id, 1);
        rplf.setLocation(this.getLocation());
        rplf.setResizable(false);
        rplf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        OrderReport orf = new OrderReport(this.email);
        orf.setLocation(this.getLocation());
        orf.setResizable(false);
        orf.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
